name: Build

on: [push, pull_request]

jobs:
  Build:

    runs-on: ubuntu-latest
    container: nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04

    steps:
      - name: Install git
        run: |
          apt-get -y update
          apt-get install -y git

      # - name: Install conda
      #   uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     python-version: 3.9

      - name: Install cmake
        uses: jwlawson/actions-setup-cmake@v1.12

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - run: |
          whoami
          pwd
          ls -alh

      - name: Install python deps
        run: pip install -r requirements.txt
      
