name: Build

on: [push, pull_request]

jobs:
  Build:
    defaults:
      run:
        # Conda needs a login shell to activate the conda environment
        shell: bash -l {0}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9

      - name: Install python deps
        run: pip install -r requirements.txt

      - uses: jwlawson/actions-setup-cmake@v1.12

      - name: Build
        run: |
          mkdir build
          cd build
          ../config/config.linux
          make
